# Generated by Django 2.2.7 on 2019-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kod_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
